name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: File Regex Replace
        uses: mingjun97/file-regex-replace@v1
        with:
          # regex to apply(regex)
          regex: '<!-- Placeholder -->'
          # flags of the regex
          flags: "g" # optional, default is g
          # replacement string
          replacement: '<tr><td>1</td><td>name</td><td>location goes here</td></tr><tr><td>2</td><td>Alen</td><td>2nd location goes here</td></tr>'
          # Files to be replaced(regex)
          include: '.*'
          # Files not to be replaced(regex)
          exclude: '.^' # optional, default is .^
          # String file encoding
          encoding: 'utf8' # optional, default is utf8
          # Path to the folder to be replaced
          path: .
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_BLACK_GRASS_0D1A55410 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/src" # App source code path
          api_location: "" # Api source code path - optional
          output_location: "" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_BLACK_GRASS_0D1A55410 }}
          action: "close"
